version: "3.8"

services:
  infections-db:
    image: postgres:15
    container_name: infections-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql:z
      - ./database/test_data.sql:/docker-entrypoint-initdb.d/02-test_data.sql:z
    networks:
      - archi_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  infections-service:
    build: .
    container_name: infections-service
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: postgresql+psycopg://${DB_USER}:${DB_PASSWORD}@infections-db:5432/${DB_NAME}
    depends_on:
      infections-db:
        condition: service_healthy
    networks:
      - archi_network

volumes:
  pg_data:

networks:
  archi_network:
    driver: bridge
